extends: standard

env:
  es6: true

rules:
  linebreak-style: 0
  comma-dangle: ["error", "never"]
  no-multi-spaces: ["error", { ignoreEOLComments: true, exceptions: { "VariableDeclarator": true, "ImportDeclaration": true, "AssignmentExpression": true } }]
  no-console: ["error", { allow: ["warn", "error", "info"] }]
  import/no-unresolved: [2, { commonjs: false, amd: false }]
  func-names: ["error", "as-needed"]
  no-param-reassign: ["error", { "props": false }]
  no-restricted-properties: [2, {"object": "disallowedObjectName", "property": "disallowedPropertyName"}]
  no-unused-expressions: ["error", { "allowShortCircuit": true, "allowTernary": true }]
  no-underscore-dangle: ["error", { "allow": ["_exec"] }]
  import/no-extraneous-dependencies: ["error", {"devDependencies": true, "optionalDependencies": false, "peerDependencies": false}]
  prefer-arrow-callback: ["error", { "allowNamedFunctions": true }]
  arrow-body-style: ["error", "as-needed", { "requireReturnForObjectLiteral": false }]
  prefer-destructuring: ["error", {AssignmentExpression: {object: false}}]
