set -ag terminal-overrides ",xterm-256color:RGB"
set -g default-terminal "tmux-256color"

set -g prefix C-a
unbind C-b
bind-key C-a send-prefix

unbind c
bind c new-window -c $HOME

unbind %
bind | split-window -h -c "#{pane_current_path}"

unbind '"'
bind - split-window -v -c "#{pane_current_path}"

unbind r
bind r source-file ~/.tmux.conf

# resize panes
bind -r j resize-pane -D 5
bind -r k resize-pane -U 5
bind -r l resize-pane -R 5
bind -r h resize-pane -L 5

# fullscreen pane
bind -r m resize-pane -Z
set -g mouse on

set-window-option -g mode-keys vi
bind-key -T copy-mode-vi 'v' send -X begin-selection # start selecting text with "v"
bind-key -T copy-mode-vi 'y' send -X copy-selection # copy text with "y"
unbind -T copy-mode-vi MouseDragEnd1Pane

## tpm plugin, install from: git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'tmux-plugins/tmux-logging'

## tmux plugins
set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'fabioluciano/tmux-tokyo-night'
set -g @plugin 'tmux-plugins/tmux-continuum'

## Resurrect
set -g @resurrect-capture-pane-contents 'on'
set -g @continuum-restore 'on'

## Tokyonight
set -g @powerkit_status_position            "bottom"
set -g @powerkit_theme                      "tokyo-night"
set -g @powerkit_theme_variant              "night"
set -g @powerkit_status_position            "bottom"
set -g @powerkit_transparent                "true"
set -g @powerkit_edge_separator_style       "slant"
set -g @powerkit_elements_spacing           "false"
set -g @powerkit_icon_padding               "2"
set -g @powerkit_plugins                    "git"
set -g @powerkit_plugin_group_colors        "window-active-base-darker"
set -g @powerkit_active_window_show_index   "false"
set -g @powerkit_inactive_window_show_index "false"

## resurrect path
set -g @resurrect-dir '~/.tmux/tmux_resurrect'

## Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
