#!/bin/bash

sshdir="${HOME}/.ssh"

setup_gitconfig () {
  printf "\e[1;33m  --> Setting up your Git global Configuration\e[0m\n"
  read -p "      * Your Git Author Name: " GIT_AUTHOR_NAME
  read -p "      * Your Git Author Email: " GIT_AUTHOR_EMAIL

  git config --global user.name "${GIT_AUTHOR_NAME}"
  git config --global user.eamail "${GIT_AUTHOR_EMAIL}"

  git config --global push.default simple
  git config --global alias.lg "log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit --date=relative"

  printf "\n\e[0;34m  --> Would you like to keep setting up your git?
    Select which task to run next:

    [2] Github: Create and Add SSH Keys
    [3] Bitbucket: Create and Add SSH Keys
    [Q/q] Type Quit to cancel
  \e[0m"

  read -p "
  --> Answer: " selected

    case "${selected}" in
      [g]*) setup_github_ssh; break;;
      [b]*) setup_bitbucket_ssh; break;;
      [Q/q]*) exit;;
    esac
}

setup_github_ssh () {
  printf "\e[1;33m  --> Setting up your Github SSH Keys\e[0m\n"
  read -p "      * Please enter your github email: " GITHUB_EMAIL
  read -p "      * Please add a title to your key: " GITHUB_TITLE
  echo -n "      * Please enter a new Passphrase:  "
  read -s PASSPHRASE

  echo ""
  ssh-keygen -t rsa -C "${GITHUB_EMAIL}" -f "${sshdir}/github_rsa" -P "${PASSPHRASE}" -q
  ssh-add "${sshdir}/github_rsa" && pbcopy < "${sshdir}/github_rsa.pub"

  GITHUB_KEY=`pbpaste`
  GITHUB_PAYLOAD="{ \"title\": \"$GITHUB_TITLE\", \"key\": \"$GITHUB_KEY\" }"

  printf "\n\e[1;33m  --> Okay, now I will need you to login to Github and
      authorize me to add these SSH Key under your account\n\e[0m"

  read -p "      * Github Username: " GH_USERNAME
  echo -n "      * Github Password: "
  read -s GH_PASSWORD

  printf "\n\e[0;1m   --> Adding the SSH Key to your Github Account
       Hang Tight! this won't be long..\n\n\e[0m"

  echo $(curl --user "${GH_USERNAME}:${GH_PASSWORD}" -X POST --data "${GITHUB_PAYLOAD}" https://api.github.com/user/keys -#o /dev/null)

  printf "\n\e[0;32m  --> SSH Key has been successfully added!
  --> Accessing Github to verify the SSH Keys\e[0m\n\n"
  ssh -T git@github.com

  echo ""
  exit 0
}

setup_bitbucket_ssh () {
  printf "\e[1;33m  --> Setting up your Bitbucket SSH Keys\e[0m\n"
  read -p "      * Please enter your Bitbucket Username: " BITBUCKET_USERNAME
  echo -n "      * Please enter your Bitbucket Password: "
  read -s BITBUCKET_PASSWORD
  echo ""


  read -p "      * Please add a title to your key: " BITBUCKET_TITLE
  echo -n "      * Please enter a new Passphrase:  "
  read -s PASSPHRASE

  ssh-keygen -q -f "${sshdir}/bitbucket_rsa" -P "${PASSPHRASE}" && pbcopy < "${sshdir}/bitbucket_rsa.pub"

  BITBUCKET_KEY=`pbpaste`
  BITBUCKET_PAYLOAD="{ \"label\": \"${BITBUCKET_TITLE}\", \"key\": \"${BITBUCKET_KEY}\" }"

  printf "\n\e[1;33m  --> Okay, since you've entered your Bitbucket credentials,
      I will now use the authorization to add these SSH Keys to your account.
      Hang tight! this won't be long \n\n\e[0m"

  echo $(curl --user "${BITBUCKET_USERNAME}:${BITBUCKET_PASSWORD}" -X POST --data "${BITBUCKET_PAYLOAD}" "https://bitbucket.org/api/1.0/users/${BITBUCKET_USERNAME}/ssh-keys/" -H "Content-Type: application/json" -#o /dev/null)
  printf "\n\e[0;32m  --> SSH Key has been successfully added!
  --> Accessing Bitbucket to verify the SSH Keys\e[0m\n\n"
  ssh -T git@bitbucket.org

  echo ""
  exit 0
}

printf "\e[0;1m
  Hey, let's go get your Git configured for optimum awesome! Here are some tasks
  I can perform for you, all you have to do is fill in the blanks and everything
  will be effin splendid!\e[0m

  \e[0;34mPlease select the task you'd like to run:

    [1] Setup your global Git Configuration
    [2] Github: Create and Add SSH Keys
    [3] Bitbucket: Create and Add SSH Keys
    [4] All of the above
    [Q] None of the above, Quit this setup\e[0m

  \e[0;1mWhenever you're ready, select your answer and hit return!
\e[0m"

while true; do
  read -p "  --> Answer: " ANSWER
  echo " "
  case $ANSWER in
    [1]*) setup_gitconfig; break;;
    [2]*) setup_github_ssh; break;;
    [3]*) setup_bitbucket_ssh; break;;
    # [4]*) setup_all; break;;
    [Q/q]*) exit;;
    *) echo -e "  Please select from the options above"
  esac
done
