#!/usr/bin/sh

# Ask for the administrator password upfront
sudo -v

# Copy Consolas Font to Font Library
cp -R "{$HOME}/dotfiles/osx/custom/fonts/*" "{$HOME}/Library/Fonts/"

# Copy custom preferences to ~/Library/Preferences
cp -R "{$HOME}/dotfiles/osx/custom/preferences" "{$HOME}/Library/Preferences/"

# Launchpad installation is manual at the moment
# ...

logout() {
  osascript -e 'tell application "System Events" to log out'
  builtin logout
}

logout