#!/usr/bin/sh

# ---------------------------------------------------------------------------
# Custom Everything:
#   - Finder: Sidebar List
#   - Desktop
#   - Dock
#   - Launchpad
# ---------------------------------------------------------------------------



# Add Applications to Launchpad
# ---------------------------------------------------------------------------

# Reset Launchpad
# Clear applications listed in Launchpad
rm -rf "$HOME/Library/Application Support/Dock/desktoppicture.db"
sqlite3 "$HOME/Library/Application Support/Dock/*.db" "DELETE from apps; DELETE from groups WHERE title<>''; DELETE from items WHERE rowid>2;"
killall Dock

# Add only the applications that are mostly used:

sudo ln -sf "/Applications/Reminders.app" "/Applications/Reminders.app"
sudo ln -sf "/Applications/Notes.app"     "/Applications/Notes.app"
sudo ln -sf "/Applications/Calendar.app"  "/Applications/Calendar.app"
sudo ln -sf "/Applications/App Store.app"  "/Applications/App Store.app"
sudo ln -sf "/Applications/Messages.app"  "/Applications/Messages.app"


# Add iOS Simulator to Launchpad
sudo ln -sf "/Applications/Xcode.app/Contents/Applications/iPhone Simulator.app" "/Applications/iOS Simulator.app"
